language: elixir
sudo: false
elixir:
  - 1.6
  - 1.7
otp_release:
  - 20.0
  - 20.1
  - 20.2
  - 20.3
before_script:
  - mix deps.get --only test

script: mix test

after_script:
  - MIX_ENV=test mix compile && mix coveralls.travis
#   - MIX_ENV=docs mix deps.get
#   - MIX_ENV=docs mix inch.report

notifications:
  recipients:
    - travis@coryodaniel.com
